version: '3.0'
services:


  bot:
    build: .
    volumes: 
      - .:/opt/
    working_dir: /opt/Ceub-DBot
    environment:
      ENV: development
    command: "bash -c 'rm -rf node_modules && npm i && npm run dev'"
