version: '3.0'
services:
  db:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: uniceub
      MYSQL_DATABASE: discord_dev
  #db2:
  #  image: postgres:latest
  #  ports:
  #    - 5432:5432
  #  environment:
  #    POSTGRES_PASSWORD: uniceub
  #    POSTGRES_USER: uniceub
  #    POSTGRES_DB: discord_dev
  #    LANG: en_US.utf8
  bot:
    build: ./Ceub-DBot
    volumes: 
      - ./Ceub-DBot:/opt/Ceub-DBot
    working_dir: /opt/Ceub-DBot
    environment:
      ENV: development
      DB_USER: root
      DB_PASSWORD: uniceub
      DB_NAME: discord_dev
      DB_HOST: db
    command: "bash -c 'rm -rf node_modules; npm i && npm run dev'"
